### ISSUE TITLE
Getting the error: `serverless.variables.populateObject`

### ISSUE THREAD

**Issue by Morraycage** [sinofseven/serverless-s3-remover#25]
Hi hope you are doing well i'm using serverless `3.25.1 `

And my config is this: 

```
  s3: !Ref ServerlessDeploymentBucket
  remover:
    buckets:
      - ${self:custom.s3.Ref}
```

I installed the package as it is in the Documentation but actually i'm getting this error ..

```
TypeError: this.serverless.variables.populateObject is not a function
    at populateConfig (/builds/yourbeatmaker/monorepos/node_modules/serverless-s3-remover/index.js:96:40)
    at /builds/yourbeatmaker/monorepos/node_modules/serverless-s3-remover/index.js:107:14
    at new Promise (<anonymous>)
    at Remover.remove (/builds/yourbeatmaker/monorepos/node_modules/serverless-s3-remover/index.js:106:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async PluginManager.runHooks (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/plugin-manager.js:530:9)
    at async PluginManager.invoke (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/plugin-manager.js:563:9)
    at async PluginManager.run (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/plugin-manager.js:604:7)
    at async Serverless.run (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/serverless.js:170:5)
    at async /usr/local/share/.config/yarn/global/node_modules/serverless/scripts/serverless.js:[78](https://gitlab.com/yourbeatmaker/monorepos/-/jobs/3455077336#L78)7:9
```
Is the plugin is dead ? Because i'm not understanding do i have to set populateObject or something ? Because it's not in the documentation.

Thank you by advance

**Comment by Morraycage** [comment]
Is this plugin is an open source one ? 

Cause i cannot create a pull request to fix the issue ..

**Comment by mefengl** [comment]
@Morraycage why not publish another npm package
